Fix missing-prototypes
xfce4-cpufreq-linux-pstate.c:60:1: error: 'read_params' was used with no prototype before its definition [-Werror=missing-prototypes]
xfce4-cpufreq-utils.c:84:1: error: no previous prototype for 'cpufreq_warn_reset' [-Werror=missing-prototypes]

Signed-off-by: Olaf Hering <olaf@aepfle.de>